version: '3.7'

services: 
  server:
    container_name: ${WEB_CONTAINER_NAME}
    build: ./server
    ports:
      - ${WEB_PORT:-80}:80
    restart:  ${WEB_RESTART}
    volumes:
      - ${WEB_DATA_BIND}
      - ${WEB_PHP_INI}

  pgsql:
        container_name: ${POSTGRES_CONTAINER_NAME}
        build: ./pgsql
        ports:
            - ${POSTGRES_PORT:-5431}:5432
        restart: ${POSTGRES_RESTART}
        volumes:
            - ${POSTGRES_RUN_SQL}
            - ${POSTGRES_VOLUME_DATA}
        environment:
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_DB=${POSTGRES_DB}
            - DATABASE_HOST=${DATABASE_HOST}
            - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD} # No password is needed when this option is on
        hostname: ${POSTGRES_HOSTNAME}

  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT:-5050}:80
    restart: ${PGADMIN_RESTART}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    hostname: ${PGADMIN_HOSTNAME}
